# Generated by Django 3.1.1 on 2020-09-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200924_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default=999, max_length=50, verbose_name='Verification Code'),
        ),
    ]
